# Schemas module - Pydantic schemas

from src.schemas.common import (
    PaginatedResponse,
    MessageResponse,
    ErrorResponse,
    SuccessResponse,
    StatusResponse,
)
from src.schemas.user import (
    UserPermissions,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListItem,
    UserListResponse,
    TokenResponse,
    ChangePasswordRequest,
    LoginRequest,
    flatten_permissions,
    build_permissions_from_codes,
)
from src.schemas.role import (
    PermissionBase,
    PermissionCreate,
    PermissionResponse,
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleResponse,
    RoleAssignment,
)
from src.schemas.invoice import (
    InvoiceItemBase,
    InvoiceItemCreate,
    InvoiceItemUpdate,
    InvoiceItemResponse,
    PriceDetailResponse,
    InvoiceBase,
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceListResponse,
    LastIdResponse,
    WarrantyReturnRequest,
    WarrantyReturnStatusResponse,
    PriceUpdateRequest,
)
from src.schemas.warehouse import (
    ItemLocationBase,
    ItemLocationResponse,
    WarehouseBase,
    WarehouseCreate,
    WarehouseUpdate,
    WarehouseResponse,
    WarehouseListItem,
    WarehouseListResponse,
    PriceBase,
    PriceResponse,
    FifoPriceResponse,
    CacheStatusResponse,
)
from src.schemas.reference import (
    SupplierBase,
    SupplierCreate,
    SupplierUpdate,
    SupplierResponse,
    SupplierListResponse,
    MachineBase,
    MachineCreate,
    MachineUpdate,
    MachineResponse,
    MachineListResponse,
    MechanismBase,
    MechanismCreate,
    MechanismUpdate,
    MechanismResponse,
    MechanismListResponse,
)
from src.schemas.rental import (
    RentedItemBase,
    RentedItemCreate,
    RentedItemUpdate,
    RentedItemResponse,
    RentalWarehouseLocationResponse,
    RentalStatusUpdate,
    RentalBorrowRequest,
    RentalReturnRequest,
    MissingQuantityResponse,
)

__all__ = [
    # Common
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    "SuccessResponse",
    "StatusResponse",
    # User
    "UserPermissions",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListItem",
    "UserListResponse",
    "TokenResponse",
    "ChangePasswordRequest",
    "LoginRequest",
    "flatten_permissions",
    "build_permissions_from_codes",
    # Role
    "PermissionBase",
    "PermissionCreate",
    "PermissionResponse",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "RoleAssignment",
    # Invoice
    "InvoiceItemBase",
    "InvoiceItemCreate",
    "InvoiceItemUpdate",
    "InvoiceItemResponse",
    "PriceDetailResponse",
    "InvoiceBase",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceListResponse",
    "LastIdResponse",
    "WarrantyReturnRequest",
    "WarrantyReturnStatusResponse",
    "PriceUpdateRequest",
    # Warehouse
    "ItemLocationBase",
    "ItemLocationResponse",
    "WarehouseBase",
    "WarehouseCreate",
    "WarehouseUpdate",
    "WarehouseResponse",
    "WarehouseListItem",
    "WarehouseListResponse",
    "PriceBase",
    "PriceResponse",
    "FifoPriceResponse",
    "CacheStatusResponse",
    # Reference
    "SupplierBase",
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    "SupplierListResponse",
    "MachineBase",
    "MachineCreate",
    "MachineUpdate",
    "MachineResponse",
    "MachineListResponse",
    "MechanismBase",
    "MechanismCreate",
    "MechanismUpdate",
    "MechanismResponse",
    "MechanismListResponse",
    # Rental
    "RentedItemBase",
    "RentedItemCreate",
    "RentedItemUpdate",
    "RentedItemResponse",
    "RentalWarehouseLocationResponse",
    "RentalStatusUpdate",
    "RentalBorrowRequest",
    "RentalReturnRequest",
    "MissingQuantityResponse",
]
